/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'mekanik';
  static const String PLUGIN_VERSION = '1.6.8+1';
  static const String BG = 'assets/bg.png';
  static const String SOUND = 'assets/sounds/sound.mp3';
}
